export const placePreferences = [
    { name: "Italian Food", isSelected: false,  },
    { name: "Chinese Food", isSelected: false,  },
    { name: "Japanese Cuisine", isSelected: false,  },
    { name: "Indian Cuisine", isSelected: false,  },
    { name: "Mexican Cuisine", isSelected: false,  },
    { name: "Thai Food", isSelected: false,  },
    { name: "Vegan/Vegetarian Cuisine", isSelected: false,  },
    { name: "Fast Food Restaurants", isSelected: false,  },
    { name: "Fine Dining", isSelected: false,  },
    { name: "Cafés", isSelected: false,  },
    { name: "Pubs", isSelected: false,  },
    { name: "Wine Bars", isSelected: false,  },
    { name: "Cocktail Bars", isSelected: false,  },
    { name: "Nightclubs", isSelected: false,  },
    { name: "Sports Bars", isSelected: false,  },
    { name: "Parks", isSelected: false,  },
    { name: "Beaches", isSelected: false,  },
    { name: "Hiking Trails", isSelected: false,  },
    { name: "Botanical Gardens", isSelected: false,  },
    { name: "Lakes/Rivers", isSelected: false,  },
    { name: "Movie Theaters", isSelected: false,  },
    { name: "Concert Venues", isSelected: false,  },
    { name: "Museums", isSelected: false,  },
    { name: "Art Galleries", isSelected: false,  },
    { name: "Theaters", isSelected: false,  },
    { name: "Amusement Parks", isSelected: false,  },
    { name: "Escape Rooms", isSelected: false,  },
    { name: "Bowling Alleys", isSelected: false,  },
    { name: "Malls", isSelected: false,  },
    { name: "Boutiques", isSelected: false,  },
    { name: "Thrift Stores", isSelected: false,  },
    { name: "Farmers' Markets", isSelected: false,  },
    { name: "Gyms", isSelected: false,  },
    { name: "Yoga Studios", isSelected: false,  },
    { name: "Spas", isSelected: false,  },
    { name: "Wellness Centers", isSelected: false,  },
    { name: "Swimming Pools", isSelected: false,  },
    { name: "Libraries", isSelected: false,  },
    { name: "Historical Sites", isSelected: false,  },
    { name: "Cultural Centers", isSelected: false,  },
    { name: "Science Centers", isSelected: false,  },
    { name: "Golf Courses", isSelected: false,  },
    { name: "Tennis Courts", isSelected: false,  },
    { name: "Sports Complexes", isSelected: false,  },
    { name: "Skate Parks", isSelected: false,  },
    { name: "Rock Climbing Gyms", isSelected: false,  },
    { name: "Zoos", isSelected: false,  },
    { name: "Aquariums", isSelected: false,  },
    { name: "Playgrounds", isSelected: false,  },
    { name: "Children's Museums", isSelected: false,  },
    { name: "Train Stations", isSelected: false,  },
    { name: "Bus Stations", isSelected: false,  },
    { name: "Airports", isSelected: false,  },
    { name: "Food Festivals", isSelected: false,  },
    { name: "Music Festivals", isSelected: false,  },
    { name: "Art Fairs", isSelected: false,  },
    { name: "Community Events", isSelected: false,  },
    { name: "Coffee Shops", isSelected: false,  },
    { name: "Bookstores", isSelected: false,  },
    { name: "Pet-friendly Locations", isSelected: false,  }
  ];
  